import { readFileSync, writeFileSync, existsSync, unlinkSync } from 'fs';
import { execSync, spawn } from 'child_process';
import { parse, parseExpression } from '@babel/parser';
import babelTraverse from '@babel/traverse';
import babelGenerate from '@babel/generator';
import * as t from '@babel/types';
import { join, resolve } from 'path';
import { platform, homedir } from 'os';
import { pathToFileURL } from 'url';

const traverse = babelTraverse.default;
const generate = babelGenerate.default;
const ROOT = process.cwd();

// ── File Paths ──
const packageJsonPath = join(ROOT, 'package.json');
const packageLockPath = join(ROOT, 'package-lock.json');
const serverJsonPath = join(ROOT, 'server.json');
const smitheryJsonPath = join(ROOT, 'smithery.json');
const serverCardPath = join(ROOT, 'server-card.json');
const httpScanServerPath = join(ROOT, 'scripts', 'http-scan-server.js');
const VALID_VERSION_BUMP_TYPES = new Set(['major', 'minor', 'patch']);
const SEMVER_PATTERN = /^(\d+)\.(\d+)\.(\d+)$/;
const BABEL_PARSE_OPTIONS = { sourceType: 'module', plugins: ['importMeta'] };
const FS_MODULE_SOURCES = new Set(['fs', 'node:fs']);
const GENERATED_SERVER_CARD_COMMENT = ' Server card is auto-generated by publish.js — do not edit manually';
const STATIC_SERVER_CARD_COMMENT = 'Static server card for Smithery scanning';
const SERVER_CARD_FILE_URL = '../server-card.json';
const PUBLISH_STATE_PATHS = [
  packageJsonPath,
  packageLockPath,
  serverJsonPath,
  smitheryJsonPath,
  serverCardPath,
  httpScanServerPath,
];

// ── Helpers ──
function runCommand(command, errorMessage, extraEnv = {}) {
  console.log(`\n> Running: ${command}`);
  try {
    execSync(command, {
      stdio: ['inherit', 'inherit', 'pipe'],
      env: { ...process.env, ...extraEnv },
    });
  } catch (error) {
    const capturedStderr = error.stderr?.toString?.() ?? '';
    if (capturedStderr) process.stderr.write(capturedStderr + '\n');
    error.capturedStderr = capturedStderr;
    throw new Error(`${errorMessage} (${command})`, { cause: error });
  }
}

function classifyRegistryError(error) {
  const cause = error.cause ?? {};
  const stderr = cause.capturedStderr ?? cause.stderr?.toString?.() ?? '';
  const msg = error.message ?? '';
  if (stderr.includes('401') || stderr.includes('Unauthorized') || stderr.includes('expired')
    || msg.includes('401') || msg.includes('Unauthorized') || msg.includes('expired')) {
    return 'auth-expired';
  }
  if (stderr.includes('404') || stderr.includes('not found') || stderr.includes('NPM package')
    || msg.includes('404') || msg.includes('not found')) {
    return 'npm-missing';
  }
  return 'unknown';
}

function parseFlags(args) {
  const flags = new Set();
  const positional = [];
  for (const arg of args) {
    if (arg.startsWith('--')) flags.add(arg);
    else positional.push(arg);
  }
  return { flags, positional };
}

function createServerCardReaderInit() {
  return parseExpression(
    `JSON.parse(readFileSync(new URL('${SERVER_CARD_FILE_URL}', import.meta.url), 'utf8'))`,
    BABEL_PARSE_OPTIONS,
  );
}

function isImportMetaUrl(node) {
  return t.isMemberExpression(node)
    && t.isMetaProperty(node.object)
    && node.object.meta.name === 'import'
    && node.object.property.name === 'meta'
    && t.isIdentifier(node.property, { name: 'url' });
}

function isServerCardFileUrl(node) {
  return t.isNewExpression(node)
    && t.isIdentifier(node.callee, { name: 'URL' })
    && node.arguments.length === 2
    && t.isStringLiteral(node.arguments[0], { value: SERVER_CARD_FILE_URL })
    && isImportMetaUrl(node.arguments[1]);
}

function isServerCardReaderInit(node) {
  if (!t.isCallExpression(node)) return false;
  if (!t.isMemberExpression(node.callee)) return false;
  if (!t.isIdentifier(node.callee.object, { name: 'JSON' })) return false;
  if (!t.isIdentifier(node.callee.property, { name: 'parse' })) return false;
  if (node.arguments.length !== 1) return false;

  const [readFileCall] = node.arguments;
  return t.isCallExpression(readFileCall)
    && t.isIdentifier(readFileCall.callee, { name: 'readFileSync' })
    && readFileCall.arguments.length === 2
    && isServerCardFileUrl(readFileCall.arguments[0])
    && t.isStringLiteral(readFileCall.arguments[1], { value: 'utf8' });
}

function hasReadFileSyncImport(node) {
  return t.isImportDeclaration(node)
    && FS_MODULE_SOURCES.has(node.source.value)
    && node.specifiers.some((specifier) => (
      t.isImportSpecifier(specifier)
      && t.isIdentifier(specifier.imported, { name: 'readFileSync' })
    ));
}

function ensureReadFileSyncImport(program) {
  let lastImportIndex = -1;
  let targetImport = null;

  for (const [index, node] of program.body.entries()) {
    if (!t.isImportDeclaration(node)) continue;
    lastImportIndex = index;

    if (hasReadFileSyncImport(node)) {
      return false;
    }

    if (!FS_MODULE_SOURCES.has(node.source.value)) continue;
    if (node.specifiers.some((specifier) => t.isImportNamespaceSpecifier(specifier))) continue;

    targetImport = node;
  }

  const readFileSyncSpecifier = t.importSpecifier(
    t.identifier('readFileSync'),
    t.identifier('readFileSync'),
  );

  if (targetImport) {
    targetImport.specifiers.push(readFileSyncSpecifier);
    return true;
  }

  const importDeclaration = t.importDeclaration(
    [readFileSyncSpecifier],
    t.stringLiteral('node:fs'),
  );
  program.body.splice(lastImportIndex + 1, 0, importDeclaration);
  return true;
}

function ensureGeneratedServerCardComment(declaration) {
  const existingComments = declaration.leadingComments ?? [];
  const hasComment = existingComments.some((comment) => comment.value === GENERATED_SERVER_CARD_COMMENT);
  if (hasComment) return false;

  declaration.leadingComments = [
    ...existingComments.filter((comment) => comment.value.trim() !== STATIC_SERVER_CARD_COMMENT),
    { type: 'CommentLine', value: GENERATED_SERVER_CARD_COMMENT },
  ];
  return true;
}

function stripStaticServerCardComment(node) {
  let changed = false;

  for (const key of ['leadingComments', 'innerComments', 'trailingComments']) {
    const comments = node[key];
    if (!comments?.length) continue;

    const filteredComments = comments.filter((comment) => comment.value.trim() !== STATIC_SERVER_CARD_COMMENT);
    if (filteredComments.length === comments.length) continue;

    changed = true;
    if (filteredComments.length > 0) {
      node[key] = filteredComments;
      continue;
    }

    delete node[key];
  }

  return changed;
}

function stripStaticServerCardComments(program) {
  return program.body.reduce((changed, node) => stripStaticServerCardComment(node) || changed, false);
}

export function transformHttpScanServerSource(source) {
  const ast = parse(source, BABEL_PARSE_OPTIONS);
  let serverCardDeclaration = null;
  let serverCardDeclarator = null;

  traverse(ast, {
    VariableDeclarator(path) {
      if (!t.isIdentifier(path.node.id, { name: 'SERVER_CARD' })) return;
      serverCardDeclarator = path.node;
      serverCardDeclaration = path.parentPath.node;
      path.stop();
    },
  });

  if (!serverCardDeclarator || !serverCardDeclaration) {
    return { changed: false, code: source };
  }

  let changed = false;

  if (!isServerCardReaderInit(serverCardDeclarator.init)) {
    serverCardDeclarator.init = createServerCardReaderInit();
    changed = true;
  }

  if (ensureReadFileSyncImport(ast.program)) {
    changed = true;
  }

  if (stripStaticServerCardComments(ast.program)) {
    changed = true;
  }

  if (ensureGeneratedServerCardComment(serverCardDeclaration)) {
    changed = true;
  }

  if (!changed) {
    return { changed: false, code: source };
  }

  const output = generate(ast, {
    comments: true,
    jsescOption: { quotes: 'single', minimal: true },
  }).code;
  return { changed: true, code: source.endsWith('\n') ? `${output}\n` : output };
}

function getMcpPublisher() {
  if (platform() === 'win32') {
    const localAppData = process.env.LOCALAPPDATA || join(homedir(), 'AppData', 'Local');
    const winPath = join(localAppData, 'mcp-publisher', 'mcp-publisher.exe');
    try {
      execSync(`"${winPath}" --help`, { stdio: 'ignore' });
      return `"${winPath}"`;
    } catch {
      return 'mcp-publisher';
    }
  }
  return 'mcp-publisher';
}

export function bumpVersion(version, type) {
  const normalizedType = typeof type === 'string' ? type.trim() : '';
  const match = SEMVER_PATTERN.exec(version);

  if (!match) {
    throw new Error(`Invalid version "${version}". Expected format major.minor.patch.`);
  }

  if (!VALID_VERSION_BUMP_TYPES.has(normalizedType)) {
    throw new Error(`Invalid version bump type "${type}". Expected one of: major, minor, patch.`);
  }

  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);

  if (normalizedType === 'major') return `${major + 1}.0.0`;
  if (normalizedType === 'minor') return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

function captureFileSnapshot(filePath) {
  if (!existsSync(filePath)) {
    return { exists: false, content: '' };
  }

  return { exists: true, content: readFileSync(filePath, 'utf8') };
}

export function captureFileSnapshots(filePaths) {
  return new Map(filePaths.map((filePath) => [filePath, captureFileSnapshot(filePath)]));
}

function restoreFileSnapshot(filePath, snapshot) {
  if (snapshot.exists) {
    writeFileSync(filePath, snapshot.content);
    return;
  }

  if (existsSync(filePath)) {
    unlinkSync(filePath);
  }
}

export function revertVersionChanges(fileSnapshots) {
  console.log('\n↩️ Reverting local publish changes...');

  for (const [filePath, snapshot] of fileSnapshots.entries()) {
    try {
      restoreFileSnapshot(filePath, snapshot);
    } catch (error) {
      console.warn(`⚠️  Could not restore ${filePath}: ${error.message}`);
    }
  }
}

/**
 * Introspect the MCP server via stdio to discover tools.
 * Spawns the server, sends initialize + tools/list, captures the result.
 */
async function discoverTools() {
  console.log('\n🔍 Discovering tools from MCP server...');
  return new Promise((resolve, reject) => {
    const child = spawn('node', ['src/index.js'], {
      cwd: ROOT,
      stdio: ['pipe', 'pipe', 'pipe'],
      env: process.env,
    });

    let buffer = '';
    let tools = null;
    let phase = 'init'; // init -> list -> done
    let settled = false;
    let timedOut = false;
    let timeoutId = null;

    const cleanupListeners = () => {
      child.stdout.off('data', handleStdoutData);
      child.off('close', handleClose);
      child.off('error', handleError);
    };

    const settle = (callback) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeoutId);
      cleanupListeners();
      callback();
    };

    const handleStdoutData = (chunk) => {
      if (timedOut || settled) return;

      buffer += chunk.toString();
      // JSON-RPC messages are separated by newlines; try to parse each one
      const lines = buffer.split('\n');
      buffer = lines.pop(); // keep incomplete last line
      for (const line of lines) {
        if (timedOut || settled) break;
        if (!line.trim()) continue;
        try {
          const msg = JSON.parse(line);
          if (phase === 'init' && msg.result?.protocolVersion) {
            // Initialize succeeded, send initialized notification + tools/list
            phase = 'list';
            child.stdin.write(JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }) + '\n');
            child.stdin.write(JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} }) + '\n');
          } else if (phase === 'list' && msg.result?.tools) {
            tools = msg.result.tools;
            phase = 'done';
            child.kill();
          }
        } catch { /* not valid JSON yet */ }
      }
    };

    const handleClose = () => {
      if (timedOut || settled) return;

      if (tools) {
        settle(() => {
          console.log(`   Found ${tools.length} tools.`);
          resolve(tools);
        });
      } else {
        settle(() => reject(new Error('Failed to discover tools from MCP server.')));
      }
    };

    const handleError = (error) => {
      if (timedOut || settled) return;
      settle(() => reject(error));
    };

    child.stdout.on('data', handleStdoutData);
    child.on('close', handleClose);
    child.on('error', handleError);

    // Send initialize request
    const initMsg = JSON.stringify({
      jsonrpc: '2.0',
      id: 1,
      method: 'initialize',
      params: {
        protocolVersion: '2024-11-05',
        capabilities: {},
        clientInfo: { name: 'publish-scanner', version: '1.0.0' },
      },
    });
    child.stdin.write(initMsg + '\n');

    // Timeout after 15s
    timeoutId = setTimeout(() => {
      if (settled) return;
      timedOut = true;
      settled = true;
      clearTimeout(timeoutId);
      cleanupListeners();
      child.kill();
      reject(new Error('Timeout discovering tools.'));
    }, 15_000);
  });
}

/**
 * Generate server-card.json and update http-scan-server.js with the latest tools.
 */
function updateServerCard(tools, version) {
  const card = {
    serverInfo: { name: 'smart-terminal-mcp', version },
    tools: tools.map(t => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
    resources: [],
    prompts: [],
  };

  // Write standalone server-card.json
  writeFileSync(serverCardPath, JSON.stringify(card, null, 2) + '\n');
  console.log(`   Written server-card.json (${tools.length} tools)`);

  if (existsSync(httpScanServerPath)) {
    const { changed, code } = transformHttpScanServerSource(readFileSync(httpScanServerPath, 'utf8'));
    if (changed) {
      writeFileSync(httpScanServerPath, code);
      console.log('   Updated http-scan-server.js to read from server-card.json');
    }
  }
}

/**
 * Publish to Smithery by spinning up the HTTP scan server + cloudflare tunnel.
 */
async function publishToSmithery() {
  console.log('\n💎 Phase 3: Publishing to Smithery.ai...');
  console.log('   Starting HTTP scan server...');

  const httpServer = spawn('node', ['scripts/http-scan-server.js'], {
    cwd: ROOT,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  // Wait for server to be ready
  await new Promise((resolve) => {
    httpServer.stdout.on('data', (d) => {
      if (d.toString().includes('MCP HTTP scan server')) resolve();
    });
    setTimeout(resolve, 3000);
  });

  console.log('   Starting Cloudflare tunnel...');
  const tunnel = spawn('npx', ['-y', 'cloudflared', 'tunnel', '--url', 'http://localhost:3456'], {
    cwd: ROOT,
    stdio: ['ignore', 'pipe', 'pipe'],
    shell: true,
  });

  // Extract tunnel URL from stderr (cloudflared logs to stderr)
  const tunnelUrl = await new Promise((resolve, reject) => {
    let output = '';
    const onData = (d) => {
      output += d.toString();
      const match = output.match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/);
      if (match) resolve(match[0]);
    };
    tunnel.stderr.on('data', onData);
    tunnel.stdout.on('data', onData);
    setTimeout(() => reject(new Error('Tunnel URL not found within 30s')), 30_000);
  });

  console.log(`   Tunnel URL: ${tunnelUrl}`);
  console.log('   Publishing to Smithery...');

  try {
    const apiKey = process.env.SMITHERY_API_KEY || '';
    const envVars = apiKey ? { SMITHERY_API_KEY: apiKey } : {};
    runCommand(
      `npx smithery mcp publish "${tunnelUrl}/mcp" -n pungggi/smart-terminal`,
      'Smithery.ai publishing failed.',
      envVars,
    );
  } finally {
    tunnel.kill();
    httpServer.kill();
    console.log('   Cleaned up HTTP server and tunnel.');
  }
}

function updateVersionFiles(nextVersion) {
  const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf8'));

  console.log('📝 Updating version in package.json, package-lock.json, server.json, smithery.json...');
  pkg.version = nextVersion;
  writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n');

  try {
    const pkgLock = JSON.parse(readFileSync(packageLockPath, 'utf8'));
    pkgLock.version = nextVersion;
    if (pkgLock.packages?.['']) pkgLock.packages[''].version = nextVersion;
    writeFileSync(packageLockPath, JSON.stringify(pkgLock, null, 2) + '\n');
  } catch (error) {
    console.warn(`⚠️  Could not update package-lock.json: ${error.message}`);
  }

  [serverJsonPath, smitheryJsonPath].forEach((filePath) => {
    try {
      const json = JSON.parse(readFileSync(filePath, 'utf8'));
      json.version = nextVersion;
      if (Array.isArray(json.packages)) json.packages.forEach((pkg) => (pkg.version = nextVersion));
      writeFileSync(filePath, JSON.stringify(json, null, 2) + '\n');
    } catch (error) {
      console.warn(`⚠️  Could not update ${filePath}: ${error.message}`);
    }
  });
}

export async function main(args = process.argv.slice(2)) {
  const { flags, positional } = parseFlags(args);
  const skipNpm = flags.has('--skip-npm');
  const skipRegistry = flags.has('--skip-registry');
  const skipSmithery = flags.has('--skip-smithery');
  const otpFlag = [...flags].find((f) => f.startsWith('--otp='));
  const otp = otpFlag ? otpFlag.substring(otpFlag.indexOf('=') + 1) : undefined;
  const buildNpmPublishCmd = () => otp ? `npm publish --access public --otp=${otp}` : 'npm publish --access public';

  let fileSnapshots = null;
  let npmPublished = false;

  try {
    const versionArg = positional[0] || 'patch';
    const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
    const currentVersion = pkg.version;
    const nextVersion = bumpVersion(currentVersion, versionArg);
    fileSnapshots = captureFileSnapshots(PUBLISH_STATE_PATHS);

    console.log(`\n🚀 Starting publication of version ${nextVersion} (from ${currentVersion})`);

    // ── Step 1: Update manifests ──
    updateVersionFiles(nextVersion);

    // ── Step 2: Discover tools & generate server card ──
    const tools = await discoverTools();
    updateServerCard(tools, nextVersion);

    // ── Step 3: npm ──
    if (skipNpm) {
      console.log('\n📦 Phase 1: Publishing to npm... SKIPPED (--skip-npm)');
    } else {
      console.log('\n📦 Phase 1: Publishing to npm...');
      runCommand(buildNpmPublishCmd(), 'npm publishing failed.');
      npmPublished = true;
    }

    // ── Step 4: Official MCP Registry ──
    if (skipRegistry) {
      console.log('\n🌍 Phase 2: Publishing to Official MCP Registry... SKIPPED (--skip-registry)');
    } else {
      console.log('\n🌍 Phase 2: Publishing to Official MCP Registry...');
      const pub = getMcpPublisher();
      let attempts = 0;
      const maxAttempts = 3;

      while (attempts < maxAttempts) {
        attempts++;
        try {
          runCommand(`${pub} publish`, 'Official MCP Registry publishing failed.');
          break; // success
        } catch (error) {
          const classification = classifyRegistryError(error);

          if (classification === 'npm-missing' && !npmPublished) {
            console.log('\n🔄 Registry needs npm package. Publishing to npm first...');
            runCommand(buildNpmPublishCmd(), 'npm publishing failed.');
            npmPublished = true;
            console.log('\n🔄 Retrying registry publish...');
            continue;
          }

          if (classification === 'auth-expired') {
            if (attempts >= maxAttempts) {
              console.error(`\n❌ Auth still expired after ${maxAttempts} attempts. Giving up.`);
              throw error;
            }
            console.log(`\n🔄 Auth token expired. Re-logging in...`);
            try {
              runCommand(`${pub} login github`, 'Registry login failed.');
            } catch (loginError) {
              console.error('❌ Automatic login failed. Fix manually:');
              console.error(`   ${pub} login github`);
              throw error; // throw original registry error
            }
            console.log('🔄 Retrying registry publish...');
            continue;
          }

          throw error;
        }
      }
    }

    // ── Step 5: Smithery.ai (HTTP server + tunnel + publish) ──
    if (skipSmithery) {
      console.log('\n💎 Phase 3: Publishing to Smithery.ai... SKIPPED (--skip-smithery)');
    } else {
      await publishToSmithery();
    }

    const skipped = [skipNpm && 'npm', skipRegistry && 'registry', skipSmithery && 'smithery'].filter(Boolean);
    const suffix = skipped.length ? ` (skipped: ${skipped.join(', ')})` : ' to all registries';
    console.log(`\n✅ SUCCESSFULLY PUBLISHED version ${nextVersion}${suffix}!`);
  } catch (error) {
    console.error('\n❌ Publish failed.');
    console.error(error);
    if (fileSnapshots) {
      if (npmPublished) {
        // npm already has this version — don't revert local files or we'll get version drift.
        console.error('\n⚠️  npm was already published. Local version files kept at the new version.');
        console.error('   Fix the issue and re-run with --skip-npm to complete remaining phases.');
      } else {
        revertVersionChanges(fileSnapshots);
      }
    }
    throw error;
  }
}

function isDirectExecution() {
  return Boolean(process.argv[1]) && import.meta.url === pathToFileURL(resolve(process.argv[1])).href;
}

// ══════════════════════════════════════════════════════════
//  MAIN
// ══════════════════════════════════════════════════════════
if (isDirectExecution()) {
  try {
    await main();
  } catch {
    process.exitCode = 1;
  }
}
